### ISSUE TITLE
Repo à archiver

### ISSUE THREAD

**Issue by Seluj78** [AFPy/AfpyLogs#1]
cc @gawel : Va tu modifier des trucs la dessus ou je peux archiver le repo ?

**Comment by gawel** [comment]
C'est http://logs.afpy.org/archives/2019/11/18/
Le machin est hébergé chez moi, là.

Si vous voulez garder les logs irc, faut le garder. Sinon virer la référence qui pointe dessus sur le site web.

**Comment by JulienPalard** [comment]
C'est cool les logs !
@gawel j'ai https://github.com/AFPy/infra qui naît *tout doucement*, si tu veux qu'on reprenne l'hébergement des logs sur l'infra de l'AFPy ouvre-y une issue et je tenterai de m'en occuper.

C'est cool les logs, on archive pas le repo :)

Merci @gawel d'héberger des trucs sans qu'on s'en rende compte et qui fonctionnent sans sourciller depuis que j'suis gamin.
