### ISSUE TITLE
A minuit, quand le fichier de log n'est pas encore crée ...

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/AfpyLogs#2]
Le site ne marche pas :] (file not found).

**Comment by Seluj78** [comment]
Créé le à 23h59

**Comment by Mindiell** [comment]
La refonte devrait corriger ce souci : si un fichier n'est pas trouvé, il se rabat sur le plus récent.

**Comment by Mindiell** [comment]
On peut clore cette issue non ?

**Comment by JulienPalard** [comment]
On dirait bien oui.
